name: "Documentation"

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "src/**"
      - "*.toml"
  push:
    branches:
      - main
    tags: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  documentation:
    name: "Documentation"
    permissions:
      actions: write
      contents: write
      statuses: write
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
